:sourcesdir: ../../../../source

[[db_scripts]]
==== 创建和更新数据库的脚本

CUBA 应用程序项目总是包含两组脚本：

* 用于__创建__数据库的脚本，该脚本用于从零开始创建数据库。它们包含一组 DDL 和 DML 操作，这些操作会创建一个空数据库结构，该结构与应用程序<<data_model,数据模型>>的当前状态完全一致。这些脚本还可以使用必要的初始化数据填充数据库。

* 用于__更新__数据库的脚本，用于将数据库结构从任意一个旧的结构更新为与当前数据模型对应的结构。

更改数据模型时，必须通过 Create 和 Update 脚本使数据库结构同步相应的更改。例如，在将 `address` 属性添加到 `Customer` 实体时，有必要：

. 更改建表脚本:
+
[source, sql]
----
include::{sourcesdir}/dbms/dbscripts_1.sql[]
----
. 添加修改同一个表的更新脚本:
+
[source, sql]
----
include::{sourcesdir}/dbms/dbscripts_2.sql[]
----
+
[TIP]
====
请注意，Studio 更新脚本生成器不会跟踪属性 *Column definition* 和自定义<<datatype,数据类型>>的 `sqlType` 的更改。因此，如果更改了它们，请手动创建相应的更新脚本。
====

主数据存储的创建脚本位于 *core* 模块的 `/db/init` 目录下。附加数据存储（如果有）的创建脚本位于 `/db/init_<datastore_name>` 目录。对于应用程序支持的每种类型的 DBMS，都会创建一组单独的脚本，这些脚本位于<<cuba.dbmsType,cuba.dbmsType>>应用程序属性中指定的子目录中，例如 `/db/init/postgres`。创建脚本的名称应该符合以下格式：`++{optional_prefix}create-db.sql++`。

主数据存储的更新脚本位于 *core* 模块的 `/db/update` 目录中。附加数据存储（如果有）的更新脚本位于 `/db/update_<datastore_name>` 目录。对于应用程序支持的每种类型的 DBMS，都会创建一组单独的脚本，这些脚本位于<<cuba.dbmsType,cuba.dbmsType>>应用程序属性中指定的子目录中，例如 `/db/update/postgres`。

更新脚本有两种类型：使用 `++*.sql++` 扩展名或 `++*.groovy++` 扩展名。更新数据库的主要方法是使用 SQL 脚本。Groovy 脚本仅由<<db_update_server,数据库脚本服务器执行机制>>执行，因此它们主要用于生产环境，在数据迁移或导入无法使用纯 SQL 实现时。如果要跳过 Groovy 更新脚本，可以在命令行中运行以下命令：

[source, sql]
----
delete from sys_db_changelog where script_name like '%groovy' and create_ts > (now() - interval '1 hour')
----

更新脚本应具有特定格式的名称，更新机制会按脚本名称的字母顺序排序以形成正确的执行顺序（一般情况下，脚本名称根据创建时间来命名）。因此，在手动创建此类脚本时，建议使用以下格式指定更新脚本的名称： `{yymmdd}-{description}.sql`，其中 `yy` 表示年份，`mm` 是表示月份，`dd` 表示日期，`description` 是脚本的简短描述。例如，`121003-addCodeToCategoryAttribute.sql`。Studio 自动生成脚本时也遵循此格式。

要使用 `updateDb` 任务(gradle task)执行 groovy 更新脚本，groovy 脚本的扩展名应该是 `.upgrade.groovy`， 并且遵循相同的命名规则。注意在此时，该脚本中不允许 Post Update 操作，相同的 `ds`（访问数据源）和 `log`（访问日志记录）<<db_scripts_groovy,变量>>需要用来做数据绑定。可以通过在 `build.gradle` 的 `updateDb` 任务中设置 `executeGroovy = false` 来禁用 groovy 脚本的执行。

可以将更新脚本分组到子目录中，但是，带有子目录的脚本路径不应该违背按时间排序的顺序。例如，可以使用年份或年份和月份创建子目录。

在已部署的应用程序中，用于创建和更新数据库的脚本位于特定的<<db_dir,数据库脚本目录>>中，该目录由<<cuba.dbDir,cuba.dbDir>>应用程序属性设置。

include::db_scripts/db_scripts_sql.adoc[]

include::db_scripts/db_scripts_groovy.adoc[]

include::db_scripts/db_update_gradle.adoc[]

include::db_scripts/db_update_server.adoc[]

