:sourcesdir: ../../../../source

[[shortcuts]]
==== 键盘快捷键

本节提供可在应用程序通用用户界面中使用的键盘快捷键列表。下面列出的所有<<app_properties,应用程序属性>>都属于 `ClientConfig` 接口，可以在 Web 客户端应用程序模块中使用。

* 主应用程序窗口。

** *CTRL-SHIFT-PAGE_DOWN* – 切换到下一个标签页。由 `cuba.gui.nextTabShortcut` 属性定义。

** *CTRL-SHIFT-PAGE_UP* – 切换到上一个标签页。由 `cuba.gui.previousTabShortcut` 属性定义。

* 文件夹面板。要使用文件夹的快捷键，需要设置 <<cuba.web.foldersPaneEnabled,cuba.web.foldersPaneEnabled>> 属性为 `true`。

** *ENTER* – 打开选择的<<folders_pane,文件夹>>。

** *SPACE* - 选择/取消选择获得焦点的文件夹。

** *ARROW UP* 、 *ARROW DOWN* - 切换文件夹。

** *ARROW LEFT* 、 *ARROW RIGHT* - 折叠/展开包含子文件夹的文件夹或跳转到已有文件夹。

* 界面。

** *ESCAPE* – 关闭当前<<abstractWindow,界面>>。由 `cuba.gui.closeShortcut` 属性定义。

** *CTRL-ENTER* – 关闭当前<<abstractEditor,编辑器>>并保存更改。由 `cuba.gui.commitShortcut` 属性定义。

* 列表组件（<<gui_Table,表格>>、<<gui_GroupTable,分组表格>>、<<gui_TreeTable,树形表格>>、<<gui_Tree,树>>）的标准操作。除了这些应用程序属性之外，还可以通过调用其 `setShortcut()` 方法来设置特定操作的快捷键。

** *CTRL-\* – 调用 <<createAction,CreateAction>>。由 `cuba.gui.tableShortcut.insert` 属性定义。

** *CTRL-ALT-\* – 调用 <<addAction,AddAction>>。由 `cuba.gui.tableShortcut.add` 属性定义。

** *ENTER* – 调用 <<editAction,EditAction>>。由 `cuba.gui.tableShortcut.edit` 属性定义。

** *CTRL-DELETE* – 调用 <<removeAction,RemoveAction>> 和 <<excludeAction,ExcludeAction>>。由 `cuba.gui.tableShortcut.remove` 属性定义。

* 下拉列表（<<gui_LookupField,LookupField>> 、<<gui_LookupPickerField,LookupPickerField>>）。

** *SHIFT-DELETE* – 清除值。

* Lookup 控件的标准操作（<<gui_PickerField,PickerField>>、<<gui_LookupPickerField,LookupPickerField>>、<<gui_SearchPickerField,SearchPickerField>>）。除了这些应用程序属性外，还可以通过调用其 `setShortcut()` 方法来设置特定操作的快捷键。

+
--
** *CTRL-ALT-L* – 调用 <<lookupAction,LookupAction>>。由 `cuba.gui.pickerShortcut.lookup` 定义。

** *CTRL-ALT-O* – 调用 <<openAction,OpenAction>>。由 `cuba.gui.pickerShortcut.open` 属性定义。

** *CTRL-ALT-C* – 调用 <<clearAction,ClearAction>>。由 `cuba.gui.pickerShortcut.clear` 属性定义。

除了这些快捷键外，Lookup 控件还支持使用 CTRL-ALT-1 、CTRL-ALT-2 等操作调用，具体取决于操作个数。如果点击 CTRL-ALT-1，将调用列表中的第一个操作；点击 CTRL-ALT-2 调用第二个操作等。CTRL-ALT 组合可以替换为 `cuba.gui.pickerShortcut.modifiers` 属性中指定的任何其它组合。

--

* <<gui_Filter,Filter>> 组件。

** *SHIFT-BACKSPACE* – 打开过滤器选择弹出窗口。由 `cuba.gui.filterSelectShortcut` 属性定义。

** *SHIFT-ENTER* – 应用选择的过滤器。由 `cuba.gui.filterApplyShortcut` 属性定义。

