:sourcesdir: ../../../../../source

[[opening_screens]]
===== 打开界面

可以通过<<menu.xml,主菜单>>、<<url_history_navigation,URL 导航>>、<<standard_actions,标准操作>>（当使用浏览和编辑实体界面时）或从另外一个界面以编程方式打开。在本节，将介绍如何以编程的方式打开界面。

'''

<<screens_intf,使用 Screens 接口>>

<<screenBuilders,使用 ScreenBuilders bean>>

<<screen_parameters,传递参数给界面>>

<<screen_return_values,关闭界面后执行代码以及关闭界面返回值>>

'''

[[screens_intf]]
使用 Screens 接口::
+
--
`Screens` 接口允许创建和显示任何类型的界面。

假设有一个用于显示具有一些特殊格式的消息的界面：

.界面控制器
[source, java]
----
include::{sourcesdir}/gui/screens/screens_1.java[]
----
<1> - 一个界面参数

.界面描述
[source, xml]
----
include::{sourcesdir}/gui/screens/screens_1.xml[]
----

那么可以从另一个界面创建并打开它，如下所示：

[source, java]
----
include::{sourcesdir}/gui/screens/screens_2.java[]
----

请注意这里是如何创建界面实例、为其提供参数，然后显示界面。

如果界面不需要来自调用方的任何参数，可以仅用一行代码创建并打开它：

[source, java]
----
include::{sourcesdir}/gui/screens/screens_3.java[]
----

[WARNING]
====
`screens` 不是 Spring bean，所以只能将它注入到界面控制器或使用 `ComponentsHelper.getScreenContext(component).getScreens()` 静态方法获取。
====
--

[[screenBuilders]]
使用 ScreenBuilders bean::
+
--
通过 `ScreenBuilders` bean 可以使用各种参数打开所有类型的界面。下面是用它打开界面并且在界面关闭之后执行一些代码的例子（更多细节参考<<screen_return_values,这里>>）：

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_withAfterCloseListener.java[]
----

下面我们看看如何操作编辑界面和查找界面。注意，在大多数情况下你会使用 <<standard_actions,标准操作>>（比如 <<CreateAction>> 或 <<LookupAction>>）来打开这类界面，所以并不是非要直接用 `ScreenBuilders` API。但是，如果不用标准的操作而是想通过 <<baseAction>> 或者 <<gui_Button>> 处理打开界面的话，可以参考下面的例子。

为 `Customer` 实体实例打开默认编辑界面的示例：

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor.java[]
----

在这种情况下，编辑界面将更新实体，但调用界面将不会接收到更新后的实例。

我们经常需要编辑某些用 `Table` 或 `DataGrid` 组件显示的实体。那么应该使用以下调用方式，它更简洁且能自动更新表格组件：

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor_2.java[]
----

要创建一个新的实体实例并打开它的编辑界面，只需在构建器上调用 `newEntity()` 方法：

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor_3.java[]
----

[TIP]
====
默认编辑界面的确定过程如下：

. 如果存在使用<<PrimaryEditorScreen_annotation,@PrimaryEditorScreen>>注解的编辑界面，则使用它。
. 否则，使用 id 是 `++<entity_name>.edit++` 的编辑界面（例如，`sales_Customer.edit`）。
====

界面构建器提供了许多方法来设置被打开界面的可选参数。例如，以下代码以对话框的方式打开的特定编辑界面，同时新建并初始化实体：

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_editor_4.java[]
----

实体查找界面也能使用不同参数打开。

下面是打开 `User` 实体的默认查找界面的示例：

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_lookup.java[]
----

如果需要将找到的实体设置到字段，可使用更简洁的方式：

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_lookup_2.java[]
----

[TIP]
====
默认查找界面的确定过程如下：

. 如果存在使用<<PrimaryLookupScreen_annotation,@PrimaryLookupScreen>>注解的查找界面，则使用它。
. 否则，如果存在 id 为 `++<entity_name>.lookup++` 的界面，则使用它（例如，`sales_Customer.lookup`）。
. 否则，使用 id 为 `++<entity_name>.browse++` 的界面（例如，`sales_Customer.browse`）。
====

与使用编辑界面一样，使用构建器方法设置打开界面的可选参数。例如，以下代码以对话框的方式打开特定的查找界面，在这个界面中查找 `User` 实体：

[source, java]
----
include::{sourcesdir}/gui/screens/screenBuilders_lookup_3.java[]
----
--

[[screen_parameters]]
为界面传递参数::
+
--
为打开界面传递参数的推荐方式是使用界面控制器的公共 setter 方法，如<<screens_intf,上面界面接口>>部分示范。

使用这个方式，可以为任意类型的界面传递参数，包括使用<<screenBuilders,ScreenBuilders>>或者从<<menu.xml_screen_properties,主菜单>>打开的实体编辑和查找界面。带有传参使用 `ScreenBuilders` 来调用 `FancyMessageScreen` 如下所示：

[source, java]
----
include::{sourcesdir}/gui/screens/passing_parameters_1.java[]
----

如果使用类似 <<CreateAction>> 的标准操作打开界面，可以用它的 `screenConfigurer` 处理器通过界面的公共 setters 传递参数。

另一个方式是为参数定义一个特殊的类，然后在界面构造器中将该类的实例传递给标准的 `withOptions()` 方法。参数类必需实现 `ScreenOptions` 标记接口。示例：

[source, java]
----
include::{sourcesdir}/gui/screens/passing_options_1.java[]
----

在打开的 `FancyMessageScreen` 界面，可以通过<<screen_InitEvent,InitEvent>>和<<screen_AfterInitEvent,AfterInitEvent>>处理器获取参数：

[source, java]
----
include::{sourcesdir}/gui/screens/passing_options_2.java[]
----

带有传递 `ScreenOptions` 参数使用 `ScreenBuilders` 来调用 `FancyMessageScreen` 如下所示：

[source, java]
----
include::{sourcesdir}/gui/screens/passing_options_3.java[]
----

可以看到，这个方式需要在控制界接收参数的时候进行类型转换，所以需要考虑清楚再使用。推荐还是用上面介绍的类型安全的使用 setter 的方式。

如果使用类似 <<CreateAction>> 的标准操作打开界面，可以用它的 `screenOptionsSupplier` 处理器创建并初始化所需的 `ScreenOptions` 对象。

如果界面是基于<<abstractFrame_openWindow,legacy API>>从另一个界面打开的，那么使用 `ScreenOptions` 对象是唯一能获取到参数的方法。此时，参数对象是 `MapScreenOptions` 类型的，可以在打开的界面中按照如下处理：

[source, java]
----
include::{sourcesdir}/gui/screens/passing_options_4.java[]
----
--

[[screen_return_values]]
关闭界面后执行代码以及关闭界面返回值::
+
--
每个界面在关闭时都会发送 `AfterCloseEvent` 事件。可以为界面添加监听器，这样可以在界面关闭时收到通知，示例：

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_1.java[]
----

当使用 `ScreenBuilders` 时，可以在 `withAfterCloseListener()` 方法中提供监听器：

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_2.java[]
----

事件对象能提供关于界面是如何关闭的信息。信息可以有两种方式获取：一种是检测界面是否通过 `StandardOutcome` 枚举类型定义的一种标准输出关闭，另一种是获取 `CloseAction` 对象。前一种方法比较简单，但是后一种方法比较灵活。

先看看第一种方式：使用标准输出关闭界面然后在调用代码内进行检测。

将调用下面这个界面：

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_3.java[]
----
<1> - 在点击 "OK" 按钮时，设置一些结果状态，并使用 `StandardOutcome.COMMIT` 枚举值关闭界面。
<2> - 在点击 "Cancel" 按钮时，使用 `StandardOutcome.CLOSE` 关闭界面。

在 `AfterCloseEvent` 监听器使用事件的 `closedWith()` 方法检查界面是如何关闭的，并且需要的话可以读取结果：

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_4.java[]
----

从界面返回值的另一个方法是使用自定义的 `CloseAction` 实现。重写一下上面的示例，使用如下操作类：

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_5.java[]
----

然后可以使用该操作类关闭界面：

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_6.java[]
----
<1> - 在点击 "OK" 按钮时，创建自定义关闭操作，并设置结果值。
<2> - 在点击 "Cancel" 按钮时，使用框架提供的默认操作关闭界面。

在 `AfterCloseEvent` 监听器从事件获取 `CloseAction` 并读取结果：

[source, java]
----
include::{sourcesdir}/gui/screens/return_values_7.java[]
----

可以看到，当使用自定义的 `CloseAction` 返回值时，调用方不需要知道打开的界面类是什么，因为不会调用具体的界面控制器内的方法。所以界面可以只通过其字符串 id 来创建。

当然，在使用 `ScreenBuilders` 打开界面时，也可以使用相同的方式通过关闭操作返回结果。
--
