:sourcesdir: ../../../../../../source

[[gui_Label]]
====== 标签组件

++++
<div class="manual-live-demo-container">
    <a href="https://demo.cuba-platform.cn/sampler/open?screen=simple-label" class="live-demo-btn" target="_blank">在线示例</a>
</div>
++++

++++
<div class="manual-live-demo-container">
    <a href="http://files.cuba-platform.com/javadoc/cuba/7.2/com/haulmont/cuba/gui/components/Label.html" class="api-docs-btn" target="_blank">API 文档</a>
</div>
++++

`Label` 组件可以展示静态文本或者实体属性值。

该组件的 XML 名称是： `label`

下面是使用从<<message_packs,本地化消息包>>中获取文本来设置标签的例子:

[source, xml]
----
include::{sourcesdir}/gui_vcl/label_1.xml[]
---- 

[[gui_Label_value]]
`value` 属性设置标签的文本值。

在网页端，如果 `value` 属性设置的文本长度超出<<gui_attr_width,width>>值，文件会被分为多行显示。因此，显示一个多行标签，可以通过设置标签 <<gui_attr_width,width>>值实现. 如果文本过长但是 <<gui_attr_width,width>>值未定，文本会被截取。

[source, xml]
----
include::{sourcesdir}/gui_vcl/label_2.xml[]
----

可以在界面控制器中设置标签的参数，前提是给标签控件设置一个 id，然后在界面控制器中获取它的引用：

[source, xml]
----
include::{sourcesdir}/gui_vcl/label_3.xml[]
----

[source, java]
----
include::{sourcesdir}/gui_vcl/label_4.java[]
---- 

`Label` 组件还可以显示实体属性值。这种情况需要设置 <<gui_attr_dataContainer,dataContainer>> 和 <<gui_attr_property,property>> 属性，例如：

[source, xml]
----
include::{sourcesdir}/gui_vcl/label_5.xml[]
---- 

上面例子里，标签组件显示 `customerDс` 数据容器中实体 `Customer` 的 `name` 字段。

[[gui_Label_htmlEnabled]]
`htmlEnabled` 属性控制如何解析 <<gui_Label_value,value>> 属性值：如果 `htmlEnabled="true"`，则 `value` 值以 HTML 代码解析，否则按纯文本解析。

[[gui_Label_stylenames]]
标签样式::
+
--
在基于 Halo 主题的网页端, 可以通过 `stylename` 属性定义样式。在 XML 描述里或者在界面控制器中：
[source, xml]
----
include::{sourcesdir}/gui_vcl/label_6.xml[]
----
通过代码设置样式时，选择 `HaloTheme` 类中以 `LABEL_` 开头的常量：
[source, java]
----
include::{sourcesdir}/gui_vcl/label_7.java[]
----

[[gui_label_bold]]
* `bold` - 加粗。适用于重要的或者需要突出显示的文本。

[[gui_label_colored]]
* `colored` - 彩色文本。

[[gui_label_failure]]
* `failure` - 失败标签样式。标签外会有一个边框，文本旁边会有一个图标。适用于一些组件内部的上下文通知。

[[gui_label_h1]]
* `h1` - 标题样式，应用程序标题。

[[gui_label_h2]]
* `h2` - 标题样式，应用程序中章节标题。

[[gui_label_h3]]
* `h3` - 标题样式，应用程序子章节标题。

[[gui_label_h4]]
* `h4` - 标题样式，应用程序小章节标题。

[[gui_label_light]]
* `light` - 纤细。适用于附加/补充文本。

[[gui_label_no-margin]]
* `no-margin` - 不要默认边距。

[[gui_label_spinner]]
* `spinner` - 回旋样式。添加到空 `Label` 组件则可以创建一个可用于表示任务进行中（比如数据正在加载中...）的旋转图标。

[[gui_label_success]]
* `success` - 成功标签样式。标签外会有一个边框，文本旁会有一个图标。适用于一些组件内部的上下文通知。

--

'''

Label 组件的属性列表::
<<gui_attr_align,align>> -
<<gui_attr_css,css>> -
<<gui_attr_dataContainer,dataContainer>> -
<<gui_attr_datasource,datasource>> -
<<gui_attr_description,description>> -
<<gui_attr_descriptionAsHtml,descriptionAsHtml>> -
<<gui_attr_enable,enable>> -
<<gui_attr_expandRatio,box.expandRatio>> -
<<gui_attr_height,height>> -
<<gui_Label_htmlEnabled,htmlEnabled>> -
<<gui_attr_icon,icon>> -
<<gui_attr_id,id>> -
<<gui_attr_property,property>> -
<<gui_attr_stylename,stylename>> -
<<gui_Label_value,value>> -
<<gui_attr_visible,visible>> -
<<gui_attr_width,width>>

Label 组件的元素::
<<gui_formatter,formatter>>

Label 组件样式::
<<gui_label_bold,bold>> -
<<gui_label_colored,colored>> -
<<gui_label_failure,failure>> -
<<gui_label_h1,h1>> -
<<gui_label_h2,h2>> -
<<gui_label_h3,h3>> -
<<gui_label_h4,h4>> -
<<gui_attr_stylename_huge,huge>> -
<<gui_attr_stylename_large,large>> -
<<gui_label_light,light>> -
<<gui_label_no-margin,no-margin>> -
<<gui_attr_stylename_small,small>> -
<<gui_label_spinner,spinner>> -
<<gui_label_success,success>> -
<<gui_attr_stylename_tiny,tiny>>

API::
<<gui_api_addValueChangeListener,addValueChangeListener>>

'''

