:sourcesdir: ../../../../../../source

[[RemoveAction]]
====== RemoveAction

RemoveAction 是 <<standard_list_actions,列表操作>> 设计用来从 UI 的数据容器移除实体实例，同时从数据库删除。

该操作通过 `com.haulmont.cuba.gui.actions.list.RemoveAction` 类实现，在 XML 中需要使用操作属性 `type="remove"` 定义。可以用 `action` 元素的 XML 属性定义通用的操作参数，参阅 <<declarative_actions>> 了解细节。下面我们介绍 `RemoveAction` 类特有的参数。

下列参数可以通过 XML 或 Java 的方式设置：

* `confirmation` -  boolean 值，配置是否需要在移除选中实体之前展示确认对话框。默认为 true。

* `confirmationMessage` - 确认窗口的消息。默认从主消息包的 `dialogs.Confirmation.Remove` 键值获取。

* `confirmationTitle` - 确认窗口标题。默认从主消息包的 `dialogs.Confirmation` 键值获取。

比如，希望展示特殊的确认消息，可以在 XML 中如下配置：

[source,xml]
----
include::{sourcesdir}/gui/std_actions/remove/01.xml[]
----

或者，可以在界面控制器注入该操作，然后用 setter 配置：

[source,java]
----
include::{sourcesdir}/gui/std_actions/remove/02.java[]
----

现在我们看看那些只能用 Java 代码配置的参数。如果要为这些参数生成带正确注解的方法桩代码，可以用 Studio 中 *Component Inspector* 工具窗口的 *Handlers* 标签页功能。

* `afterActionPerformedHandler` - 在选中实体移除之后调用的处理器。接收事件对象，可以用来获取那些选中要移除的实体。示例：
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/remove/07.java[]
----

* `actionCancelledHandler` - 当用户在确认窗口取消移除操作时会调用的方法。接收事件对象，可以用来获取那些选中要移除的实体。示例：
+
[source,java]
----
include::{sourcesdir}/gui/std_actions/remove/08.java[]
----

如果需要在该操作执行前做一些检查或者与用户做一些交互，可以订阅操作的 `ActionPerformedEvent` 事件并按需调用操作的 `execute()` 方法。操作会使用你为它定义的所有参数进行调用。下面的例子中，我们在执行操作前展示了一个确认对话框：

[source,java]
----
include::{sourcesdir}/gui/std_actions/remove/09.java[]
----

另外，还可以先订阅 `ActionPerformedEvent`，但是不调用操作的 `execute()` 方法，而是直接使用 `RemoveOperation` API 移除选中的实体。此时，会忽略所有的操作参数和行为，只能用其通用参数，比如 caption, icon 等。示例：

[source,java]
----
include::{sourcesdir}/gui/std_actions/remove/10.java[]
----