:sourcesdir: ../../../../source

[[app_lifecycle_events]]
==== 应用程序生命周期事件

CUBA 应用程序中有以下几种类型的生命周期<<events,事件>>：

[[AppContextInitializedEvent]]
AppContextInitializedEvent::
+
--
在<<appContext, AppContext>>初始化后立即触发。
此时:

* 所有<<managed_beans,bean>>都已完全初始化，并且执行了 `@PostConstruct` 方法。
* 可通过静态方法 `AppBeans.get()` 获取 bean。
* `AppContext.isStarted()` 方法返回 `false`。
* `AppContext.isReady()` 方法返回 `false`。
--

[[AppContextStartedEvent]]
AppContextStartedEvent::
+
--
在 `AppContextInitializedEvent` 之后并且运行完所有 `AppContext.Listener.applicationStarted()` 之后触发。此时：

* `AppContext.isStarted()` 方法返回 `true`。
* `AppContext.isReady()` 方法返回 `false`。
* 在中间件上，如果启用了 <<cuba.automaticDatabaseUpdate,cuba.automaticDatabaseUpdate>>应用程序属性，所有数据库更新脚本已成功执行。
--

[[AppContextStoppedEvent]]
AppContextStoppedEvent::
+
--
在应用程序关闭之前并且运行完所有 `AppContext.Listener.applicationStopped()` 之后触发。此时:

** 所有 bean 都可以运行并且可以通过 `AppBeans.get()` 方法获得。
** `AppContext.isStarted()` 方法返回 `false`。
** `AppContext.isReady()` 方法返回 `false`。
--

通过指定 `@Order` 注解可以影响监听器调用的顺序。`Events.HIGHEST_PLATFORM_PRECEDENCE` 和 `Events.LOWEST_PLATFORM_PRECEDENCE` 常量指定平台中定义的监听器的使用范围。

例如:

[source, java]
----
include::{sourcesdir}/common/appLifecycleEvents_1.java[]
----

[[ServletContextInitializedEvent]]
ServletContextInitializedEvent::
+
--
在 servlet 和应用程序上下文初始化之后触发。此时：

* 可以通过静态方法 `AppBeans.get()` 获取 bean。

* 此事件包含应用程序和 servlet 上下文，因此可以注册自定义 servlet、过滤器和监听器，请参阅<<servlet_registration>>。
--

[[ServletContextDestroyedEvent]]
ServletContextDestroyedEvent::
+
--
在 Servlet 和应用程序即将关闭时触发，在这个阶段可以手动释放资源。

例如:

[source, java]
----
include::{sourcesdir}/common/events_servlet_context.java[]
----
--

